[2024-12-07T22:07:23.966+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T22:07:14.601910+00:00 [queued]>
[2024-12-07T22:07:23.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T22:07:14.601910+00:00 [queued]>
[2024-12-07T22:07:23.972+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-07T22:07:23.979+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-12-07 22:07:14.601910+00:00
[2024-12-07T22:07:23.984+0000] {standard_task_runner.py:60} INFO - Started process 19967 to run task
[2024-12-07T22:07:23.987+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'insert_book_data', 'manual__2024-12-07T22:07:14.601910+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpvhk5pv69']
[2024-12-07T22:07:23.988+0000] {standard_task_runner.py:88} INFO - Job 414: Subtask insert_book_data
[2024-12-07T22:07:24.000+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-07T22:07:24.030+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.insert_book_data manual__2024-12-07T22:07:14.601910+00:00 [running]> on host 8271fbcad3f4
[2024-12-07T22:07:24.137+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T22:07:14.601910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T22:07:14.601910+00:00'
[2024-12-07T22:07:24.196+0000] {logging_mixin.py:188} INFO -                           city  ...         sunset_time
0                     Toulouse  ... 2024-12-07 17:17:41
1     Arrondissement de Nantes  ... 2024-12-07 17:16:58
2   Arrondissement de Grenoble  ... 2024-12-07 16:55:02
3  Arrondissement de Marseille  ... 2024-12-07 17:02:22
4       Arrondissement de Lyon  ... 2024-12-07 16:57:38
5                     Montreal  ... 2024-12-07 16:11:10
6                     New York  ... 2024-12-07 16:28:39
7                      Conakry  ... 2024-12-07 18:34:03
8                        Dakar  ... 2024-12-07 18:40:10

[9 rows x 12 columns]
[2024-12-07T22:07:24.202+0000] {base.py:83} INFO - Using connection ID 'weather_database_connection' for task execution.
[2024-12-07T22:07:24.210+0000] {logging_mixin.py:188} INFO - 0    (Toulouse, broken clouds, 5.990000000000009, 1...
1    (Arrondissement de Nantes, overcast clouds, 6....
2    (Arrondissement de Grenoble, light snow, -4.12...
3    (Arrondissement de Marseille, scattered clouds...
4    (Arrondissement de Lyon, moderate rain, 2.0300...
5    (Montreal, broken clouds, -7.149999999999977, ...
6    (New York, scattered clouds, 3.460000000000036...
7    (Conakry, overcast clouds, 27.470000000000027,...
8    (Dakar, overcast clouds, 24.75, 25.16000000000...
dtype: object
[2024-12-07T22:07:24.213+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-07T22:07:24.224+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=insert_book_data, execution_date=20241207T220714, start_date=20241207T220723, end_date=20241207T220724
[2024-12-07T22:07:24.238+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-07T22:07:24.250+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
