[2024-12-06T22:14:57.182+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.save_to_csv manual__2024-12-06T22:14:51.952478+00:00 [queued]>
[2024-12-06T22:14:57.187+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.save_to_csv manual__2024-12-06T22:14:51.952478+00:00 [queued]>
[2024-12-06T22:14:57.187+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-06T22:14:57.196+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2024-12-06 22:14:51.952478+00:00
[2024-12-06T22:14:57.201+0000] {standard_task_runner.py:60} INFO - Started process 9221 to run task
[2024-12-06T22:14:57.204+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'save_to_csv', 'manual__2024-12-06T22:14:51.952478+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpjhfjztft']
[2024-12-06T22:14:57.205+0000] {standard_task_runner.py:88} INFO - Job 95: Subtask save_to_csv
[2024-12-06T22:14:57.213+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-06T22:14:57.262+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.save_to_csv manual__2024-12-06T22:14:51.952478+00:00 [running]> on host 8a5e48d7ee4d
[2024-12-06T22:14:57.392+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T22:14:51.952478+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T22:14:51.952478+00:00'
[2024-12-06T22:14:57.415+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 76, in save_data
    data = pd.DataFrame(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 658, in _extract_index
    raise ValueError(
ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
[2024-12-06T22:14:57.432+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=save_to_csv, execution_date=20241206T221451, start_date=20241206T221457, end_date=20241206T221457
[2024-12-06T22:14:57.451+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 95 for task save_to_csv (Mixing dicts with non-Series may lead to ambiguous ordering.; 9221)
[2024-12-06T22:14:57.496+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-06T22:14:57.530+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
