[2024-12-06T20:33:35.495+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-12-06T20:33:28.709443+00:00 [queued]>
[2024-12-06T20:33:35.504+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-12-06T20:33:28.709443+00:00 [queued]>
[2024-12-06T20:33:35.505+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-06T20:33:35.516+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-12-06 20:33:28.709443+00:00
[2024-12-06T20:33:35.523+0000] {standard_task_runner.py:60} INFO - Started process 4700 to run task
[2024-12-06T20:33:35.527+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-12-06T20:33:28.709443+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpb5xpe091']
[2024-12-06T20:33:35.528+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask transform_load_weather_data
[2024-12-06T20:33:35.543+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-06T20:33:35.585+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-12-06T20:33:28.709443+00:00 [running]> on host 8a5e48d7ee4d
[2024-12-06T20:33:35.676+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T20:33:28.709443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T20:33:28.709443+00:00'
[2024-12-06T20:33:35.695+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-06T20:33:35.703+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, execution_date=20241206T203328, start_date=20241206T203335, end_date=20241206T203335
[2024-12-06T20:33:35.738+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-06T20:33:35.764+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
