[2024-12-07T21:07:43.880+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T21:07:36.714091+00:00 [queued]>
[2024-12-07T21:07:43.890+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T21:07:36.714091+00:00 [queued]>
[2024-12-07T21:07:43.890+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-07T21:07:43.898+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-12-07 21:07:36.714091+00:00
[2024-12-07T21:07:43.904+0000] {standard_task_runner.py:60} INFO - Started process 17232 to run task
[2024-12-07T21:07:43.908+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'insert_book_data', 'manual__2024-12-07T21:07:36.714091+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpazenrq8q']
[2024-12-07T21:07:43.910+0000] {standard_task_runner.py:88} INFO - Job 378: Subtask insert_book_data
[2024-12-07T21:07:43.927+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-07T21:07:43.973+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.insert_book_data manual__2024-12-07T21:07:36.714091+00:00 [running]> on host 8271fbcad3f4
[2024-12-07T21:07:44.032+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T21:07:36.714091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T21:07:36.714091+00:00'
[2024-12-07T21:07:44.081+0000] {logging_mixin.py:188} INFO -        city weather_description  ...        sunrise_time         sunset_time
0  Toulouse           clear sky  ... 2024-12-07 08:14:17 2024-12-07 17:17:41

[1 rows x 12 columns]
[2024-12-07T21:07:44.089+0000] {base.py:83} INFO - Using connection ID 'weather_database_connection' for task execution.
[2024-12-07T21:07:44.094+0000] {logging_mixin.py:188} INFO - 0    (Toulouse, clear sky, 5.990000000000009, 0.580...
dtype: object
[2024-12-07T21:07:44.095+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-07T21:07:44.104+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=insert_book_data, execution_date=20241207T210736, start_date=20241207T210743, end_date=20241207T210744
[2024-12-07T21:07:44.158+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-07T21:07:44.181+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
